---------------------------------------------------------------
-- table: policy
---------------------------------------------------------------

-- drop table policy;
create table policy
(
  policy_type character varying(40),
  policy_number integer,
  policy_name character varying(40),
  field_0 text,
  field_1 text,
  field_2 text,
  field_3 text,
  field_4 text,
  field_5 text,
  field_6 text,
  field_7 text,
  field_8 text,
  field_9 text,
  field_10 text,
  field_11 text,
  field_12 text,
  field_13 text,
  field_14 text,
  field_15 text,
  field_16 text,
  field_17 text,
  field_18 text,
  field_19 text,
  field_20 text,
  field_21 text,
  field_22 text,
  field_23 text,
  field_24 text,
  field_25 text,
  field_26 text,
  field_27 text,
  field_28 text,
  field_29 text,
  field_30 text,
  field_31 text,
  field_32 text,
  field_33 text,
  field_34 text,
  field_35 text,
  field_36 text,
  field_37 text,
  field_38 text,
  field_39 text,
  field_40 text,
  field_41 text,
  field_42 text,
  field_43 text,
  field_44 text,
  field_45 text,
  field_46 text,
  field_47 text,
  field_48 text,
  field_49 text,
  field_50 text,
  field_51 text,
  field_52 text,
  field_53 text,
  field_54 text,
  field_55 text,
  field_56 text,
  field_57 text,
  field_58 text,
  field_59 text,
  field_60 text,
  field_61 text,
  field_62 text,
  field_63 text,
  field_64 text,
  field_65 text,
  field_66 text,
  field_67 text,
  field_68 text,
  field_69 text,
  field_70 text,
  field_71 text,
  field_72 text,
  field_73 text,
  field_74 text,
  field_75 text,
  field_76 text,
  field_77 text,
  field_78 text,
  field_79 text,
  field_80 text,
  field_81 text,
  field_82 text,
  field_83 text,
  field_84 text,
  field_85 text,
  field_86 text,
  field_87 text,
  field_88 text,
  field_89 text,
  field_90 text,
  field_91 text,
  field_92 text,
  field_93 text,
  field_94 text,
  field_95 text,
  field_96 text,
  field_97 text,
  field_98 text,
  field_99 text,
  empty character(1),
  constraint pk_policy_numbertype primary key (policy_number, policy_type)
);